import 'bootstrap/dist/css/bootstrap.min.css'
import React, {useRef} from 'react'
import styles from '@/styles/Home.module.css'
import { Inter } from 'next/font/google'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export default function Contents () {
    return (
        <>
        <Head>
        <title> F-enigma </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Allura&family=Kalam:wght@300;400;700&display=swap" rel="stylesheet" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Crimson+Text:ital,wght@0,400;0,600;0,700;1,400;1,600;1,700&display=swap" rel="stylesheet"></link>
        </Head>
        <main className={`${styles.main} ${inter.className}`}>
        <div className='container mt-3'>
            <div className="row row-cols-1 row-cols-md-3 g-4">
            <div className="col">
            <div className="shadow card h-100">
                <img src="REALIZE_tokyo.jpg" className="card-img-top"/>
                <div className="card-body">
                <div className="card-text mb-2">2023.01.14-15</div>
                <a href="https://twitter.com/omunazotoki/status/1596111466217631744"><h4>REALIZE（東京）</h4></a>
                <div className="card-text"><a href="https://nazonosono.com/">上方謎の園</a>と白鷺祭で実施した「REALIZE」を東京で再演</div>
                </div>
            </div>
            </div>
            <div className="col">
            <div className="shadow card h-100">
                <img src="REALIZE_shirasagi.jpg" className="card-img-top"/>
                <div className="card-body">
                <div className="card-text mb-2">2022.11.04-06</div>
                <a href="https://twitter.com/omunazotoki/status/1581204739605159937"><h4>REALIZE（白鷺祭）</h4></a>
                <div className="card-text"><a href="https://nazonosono.com/">上方謎の園</a>で実施した「REALIZE」を白鷺祭にて再演</div>
                </div>
            </div>
            </div>
            <div className="col">
            <div className="shadow card h-100">
                <img src="REALIZE_shirasagi.jpg" className="card-img-top"/>
                <div className="card-body">
                <div className="card-text mb-2">2022.10.08-11.06</div>
                <a href="https://twitter.com/omunazotoki/status/1581204739605159937"><h4>謎解きMISSION～天空ミュージアムの謎～</h4></a>
                <div className="card-text"><a href="https://nazonosono.com/">ゴルゴ13×堺市「さいとう・たかを劇画の世界2022」</a>にて開催された子供用謎解きイベント</div>
                </div>
            </div>
            </div>
            <div className="col">
            <div className="shadow card h-100">
                <img src="REALIZE_shirasagi.jpg" className="card-img-top"/>
                <div className="card-body">
                <div className="card-text mb-2">2022.10.08-11.06</div>
                <a href="https://twitter.com/omunazotoki/status/1581204739605159937"><h4>謎解きMISSION～GET BACK THE DIAMOND～</h4></a>
                <div className="card-text"><a href="https://nazonosono.com/">ゴルゴ13×堺市「さいとう・たかを劇画の世界2022」</a>にて開催された周遊型謎解きイベント</div>
                </div>
            </div>
            </div>
            </div>
      </div>
      </main>
      </>
    )
}