import 'bootstrap/dist/css/bootstrap.min.css'
import styles from '@/styles/Home.module.css'
import Head from 'next/head'


export default function Contact() {
  return (
    <>
      <Head>
      <title> F-enigma </title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${styles.main}`}>
      <div className='container mt-1'>
          <div className={styles.LikeB}>
                <h2>〇入部希望者募集</h2>
          </div>
          <div className="p-3 mb-3 bg-white text-dark">
                <h4>
                    F-enigmaでは随時新入部員を募集しています。大阪府立大学・大阪市立大学・大阪公立大学の学生であれば、どなたでも入部できます。もちろんどのキャンパスでもOK！お気軽にご連絡ください！
                </h4>
          </div>
          <div className={styles.LikeB}>
                <h2>〇制作依頼募集</h2>
          </div>
          <div className="p-3 mb-10 bg-white text-dark">
                <h4>
                    F-enigmaでは様々な形式・媒体での謎解き制作依頼を受け付けています。具体的な内容や納期、料金についてご相談させていただきたいので、まずはご連絡ください。
                </h4>         
          </div>      
          <form action={process.env.NEXT_PUBLIC_NEWT_FORM_ENDPOINT} method="post">
          <div className='mb-3'>
              <label htmlFor='name' className='form-label'>
                <div className="p-0 mb-2 bg-white text-dark">
                お名前
                </div>
              </label>
              <input id="name" name="name" type="name" className="form-control"/>
          </div>
          <div className='mb-3'>
              <label htmlFor='email' className='form-label'>
                <div className="p-0 mb-2 bg-white text-dark">
                メールアドレス
                </div>
              </label>
              <input id="email" name="email" type="email" className="form-control"/>
          </div>
          <div className='mb-3'>
              <label htmlFor='message' className='form-label'>
                <div className="p-0 mb-2 bg-white text-dark">
                メッセージ
                </div>
                </label>
              <textarea id="message" name="message" className="form-control"></textarea>
          </div>
          <button type="submit"  className="btn btn-danger">メール送信</button>
        </form>
      </div>
      </main>
    </>
  )
}