import 'bootstrap/dist/css/bootstrap.min.css'
import React, {useRef} from 'react'
import styles from '@/styles/Home.module.css'
import Router from 'next/router'
import { Inter } from 'next/font/google'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })


export default function Contact() {
    const nameRef = useRef<HTMLInputElement>(null);
    const emailRef = useRef<HTMLInputElement>(null);
    const messageRef = useRef<HTMLTextAreaElement>(null);

    const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
        e.preventDefault();

        let data = {
            name: nameRef.current?.value,
            email: emailRef.current?.value,
            message: messageRef.current?.value,
        }

        await fetch("api/contact", {
            method: "POST",
            headers: {
                Accept: "application/json, text/plan",
                "Content-Type": "application/json",
            },
            body: JSON.stringify(data),
        }).then((res) => {
            if (res.status === 200) Router.push('success/');
        });
    };

    return (
        <>
        <Head>
        <title> F-enigma </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Allura&family=Kalam:wght@300;400;700&display=swap" rel="stylesheet" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Crimson+Text:ital,wght@0,400;0,600;0,700;1,400;1,600;1,700&display=swap" rel="stylesheet"></link>
        </Head>
        <main className={`${styles.main} ${inter.className}`}>
        <div className='container mt-3'>
            <div className="p-3 mb-2 bg-white text-dark">
                <h2 className='mb-3'>入部希望者募集</h2>
                <h4>
                    F-enigmaでは随時新入部員を募集しています。大阪府立大学・大阪市立大学・大阪公立大学の学生であれば、どなたでも入部できます。もちろんどのキャンパスでもOK！お気軽にご連絡ください！
                </h4>
            </div>
            <div className="p-3 mb-10 bg-white text-dark">
                <h2 className='mb-3'>制作依頼募集</h2>
                <h4>
                    F-enigmaでは様々な形式・媒体での謎解き制作依頼を受け付けています。具体的な内容や納期、料金についてご相談させていただきたいので、まずはご連絡ください。
                </h4>         
            </div>        
            <form onSubmit={(e: React.FormEvent<HTMLFormElement>) => handleSubmit(e)}>
                <div className='mb-3'>
                    <label htmlFor='name' className='form-label'>
                        <div className="p-0 mb-2 bg-white text-dark">
                        お名前
                        </div>
                    </label>
                    <input type='text' className='form-control' id='name' required ref={nameRef}/>
                </div>
                <div className='mb-3'>
                    <label htmlFor='email' className='form-label'>
                        <div className="p-0 mb-2 bg-white text-dark">
                        メールアドレス
                        </div>
                    </label>
                    <input type='text' className='form-control' id='email' required ref={emailRef}/>
                </div>
                <div className='mb-3'>
                    <label htmlFor='message' className='form-label'>
                        <div className="p-0 mb-2 bg-white text-dark">
                        メッセージ
                        </div>
                    </label>
                    <textarea name='message' className='form-control' id='message' ref={messageRef}/>
                </div>
                <button type='submit' className='btn btn-danger' >
                    メール送信
                </button>
            </form>
        </div>
        </main>
        </>
    )
}