import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css'


export default function Home() {
  return (
    <>
      <Head>
        <title> F-enigma </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${styles.main}`}>
        <div className='container mt-1'>
          <div className={styles.LikeB}>
            <h2>〇 Latest Topics</h2>
          </div>
          <div className='p-1 mb-3 bg-pink-200 bg-gradient text-black'>
            <h5>新歓用に動画を作りました！ぜひ見てみてください！</h5>
          </div>

          <video className='mb-5'
            src="新歓謎2024.mp4"
            muted
            style={{ height: "100%", width: "100%" }}
            controls
            autoPlay
            playsInline
          />

          <div className={styles.LikeB}>
            <h2>〇 News</h2>
          </div>
          <div className="d-grid mb-5">
            <div className='p-3 border-bottom border-text-muted bg-white text-dark'>
              <a href='https://twitter.com/omunazotoki/status/1778030166616264745' >
                <h6>2024.04.10</h6>
                <h5>2024年 新歓映像解禁！</h5>
              </a>
            </div>
            <div className='p-3 border-bottom border-text-muted bg-white text-dark'>
              <a href='https://twitter.com/omunazotoki/status/1777282789316112644' >
                <h6>2024.04.08</h6>
                <h5>2024年 新入生向けサークル紹介・新歓公演情報！</h5>
              </a>
            </div>
            <div className='p-3 border-bottom border-text-muted bg-white text-dark'>
              <a href='https://twitter.com/omunazotoki/status/1748719009577709845' >
                <h6>2024.01.20</h6>
                <h5>【再演】大阪最宴祭9 『ボムボムパニック』 再演決定</h5>
              </a>
            </div>
            <div className='p-3 border-bottom border-text-muted bg-white text-dark'>
              <a href='https://twitter.com/omunazotoki/status/1713396779641610707' >
                <h6>2023.10.15</h6>
                <h5>【新作公演】第75回白鷺祭 『ボムボムパニック』 公演決定</h5>
              </a>
            </div>
            <div className='p-3 border-bottom border-text-muted bg-white text-dark'>
              <a href='https://twitter.com/omunazotoki/status/1710136866887053433' >
                <h6>2023.10.06</h6>
                <h5>「さいとう・たかを劇画の世界2023」の企画「謎解きMISSION STOP THE JAMMER」のストーリー・謎制作担当</h5>
              </a>
            </div>
            <div className='p-3 border-bottom border-text-muted bg-white text-dark'>
              <a href='https://twitter.com/omunazotoki/status/1709821668372394042' >
                <h6>2023.10.05</h6>
                <h5>京都弁護士会 「ナゾトキ検察官の事件ファイル」ストーリー・謎制作担当</h5>
              </a>
            </div>
          </div>

          <div className={styles.LikeB}>
            <h2>〇 X</h2>
          </div>
          <a className="twitter-timeline" data-height="700" href="https://twitter.com/omunazotoki?ref_src=twsrc%5Etfw">Tweets by omunazotoki</a> <script async src="https://platform.twitter.com/widgets.js"></script>

        </div>

      </main>
    </>
  )
}
